### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yushi32** [yushi32/superior_bookmark_app#24]
### 実装予定の機能
- [ ] ソーシャルログイン機能
- [ ] ブックマーク機能
- [ ] Chrome拡張機能からのブックマーク登録
- [ ] LINE通知機能
- [ ] タグ機能
- [ ] フォルダ機能
- [ ] 検索機能
- [ ] オートコンプリート機能
- [ ] 自動タグ生成・付与機能

### 必要なページ
- [ ] トップページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] お問い合わせページ
- [ ] ブックマークページ
- [ ] マイページ

**Comment by shota-hope** [comment]
openになっているprojectsが無いのでご確認いただけますでしょうか。

**Comment by yushi32** [comment]
レビューありがとうございます。
リポジトリを紐づけるのを忘れていました。
設定しましたので、ご確認のほどよろしくお願いいたします。

**Comment by shota-hope** [comment]
提出ありがとうございます。

一例ですが、ライン通知機能は5で終わりますでしょうか？分割したほうが良さそうに思いました。
ストーリーポイント5が多いので、もう少しだけ分割してもいいかもしれません。
ご確認よろしくお願いいたします。

**Comment by yushi32** [comment]
レビューありがとうございます。
全体的に見積もりが曖昧だったので、より具体的に必要な作業を見積もってストーリーポイントの更新・issueの分割を行いました。
ご確認よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
ストーリポイント５のものはもう少し細かくしましょう。

```
# 5のストーリポイントを以下みたいな感じで細かくしましょう。

- 調査：1~2
- 〇〇ページ用意：1~2
- バックグランド：1~3
- xxページ用意：1~2
```

**Comment by yushi32** [comment]
レビューありがとうございます。
ストーリーポイントが5のissueについて複数のissueに分割しました。
ご確認よろしくお願いいたします。

**Comment by ghost** [comment]
LGTMです！

**Comment by yushi32** [comment]
ありがとうございます！
