### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by yushi32** [yushi32/superior_bookmark_app#34]
## 各種情報
サービス名：Lateless
URL：https://laterless.vercel.app

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] Googleログイン機能
- [x] ブックマーク機能
- [x] Chrome拡張機能からのブックマーク登録機能
- [x] フォルダ機能
- [x] タグ付け機能
- [x] LINE通知機能 
- [x] キーワード検索機能
- [x] タグを入力する際のオートコンプリート機能
- [x] ブックマーク登録時にドメインから自動でタグを生成・付与する機能

## READMEレビュー時から追加した機能
- [x] ドラッグ&ドロップによるブックマーク・フォルダ操作機能
  - ブックマークをフォルダに入れる
  - フォルダの階層化
  - フォルダのソート

### トップページ
[![Image from Gyazo](https://i.gyazo.com/4730bcf286017b74a565267a490492a5.png)](https://gyazo.com/4730bcf286017b74a565267a490492a5)

### ブックマーク一覧ページ
[![Image from Gyazo](https://i.gyazo.com/7cd41a5cb4155604440e45cba28376f6.png)](https://gyazo.com/7cd41a5cb4155604440e45cba28376f6)

### 検索結果ページ
[![Image from Gyazo](https://i.gyazo.com/8905f580c0a38df25a8893db8e4d434f.png)](https://gyazo.com/8905f580c0a38df25a8893db8e4d434f)

### LINE連携ページ
[![Image from Gyazo](https://i.gyazo.com/1447dd774f0a37d3c04586b0bf657ee4.png)](https://gyazo.com/1447dd774f0a37d3c04586b0bf657ee4)

### Chrome拡張機能
- ログイン前
[![Image from Gyazo](https://i.gyazo.com/90c0ee5748f988da3f22adc46429f67b.png)](https://gyazo.com/90c0ee5748f988da3f22adc46429f67b)
- ログイン後
[![Image from Gyazo](https://i.gyazo.com/c39cbc8e17a0eae277e32add702ec323.png)](https://gyazo.com/c39cbc8e17a0eae277e32add702ec323)

### LINE通知メッセージ
[![Image from Gyazo](https://i.gyazo.com/c9a84a3de36999b15085f10bba4293bf.png)](https://gyazo.com/c9a84a3de36999b15085f10bba4293bf)

**Comment by busitora** [comment]
画像だけではなく、コア機能である部分をgyazoの動画等で共有していただけますでしょうか!
ログインしてから、使うまでに理解に時間がかかるのをデモで解消するといいと思います◯

**Comment by yushi32** [comment]
ブシトラ講師、レビューありがとうございます！

> 画像だけではなく、コア機能である部分をgyazoの動画等で共有していただけますでしょうか!

コア機能であるブックマーク登録機能、タグ機能、ドラッグ&ドロップ操作について動画を用意しましたので、ご確認をお願いいたします。
LINE通知機能もコア機能ですが、そちらは先ほど掲載したスクリーンショットをご確認ください。
また、初回ログイン時に基本的な操作方法についてのツアーUIを今後追加しようと考えています。

### ブックマーク登録機能
Chrome拡張機能からブックマークを登録します。
登録したブックマークはページをリロードすることなく表示され、よく登録されるサイトにはサイト名のタグが自動で付与されます。
[![Image from Gyazo](https://i.gyazo.com/07677cffb6ecafd67b63fb3a9dc001c2.gif)](https://gyazo.com/07677cffb6ecafd67b63fb3a9dc001c2)

### タグ機能
タグの入力時には既に使用したことのあるタグがサジェストされるオートコンプリート機能を実装しました。
[![Image from Gyazo](https://i.gyazo.com/2d386834415d56a4a205e20db364921d.gif)](https://gyazo.com/2d386834415d56a4a205e20db364921d)
複数のタグでブックマークを絞り込むことが出来るので、ブックマークを便利に検索・管理出来ます。
[![Image from Gyazo](https://i.gyazo.com/ba12e08509572c6e42c4716a21daaa3b.gif)](https://gyazo.com/ba12e08509572c6e42c4716a21daaa3b)

### ドラッグ&ドロップ操作
ドラッグ&ドロップでブックマークをフォルダに登録出来ます。
[![Image from Gyazo](https://i.gyazo.com/ecc21f0be1d1ecc07eb0206e6c163a8c.gif)](https://gyazo.com/ecc21f0be1d1ecc07eb0206e6c163a8c)
フォルダ同士をドラッグ&ドロップすることで階層化が可能です。
[![Image from Gyazo](https://i.gyazo.com/f016851508ee40ae9cba9a244cfdb9ac.gif)](https://gyazo.com/f016851508ee40ae9cba9a244cfdb9ac)
フォルダ間にあるソート領域にドロップすることでフォルダを並び替えます。
[![Image from Gyazo](https://i.gyazo.com/cbdd8ce5ee3d58fce08584eecaddb7c0.gif)](https://gyazo.com/cbdd8ce5ee3d58fce08584eecaddb7c0)

**Comment by kenchasonakai** [comment]
機能確認できました！
LGTMです！

本リリースに向けて引き続き実装進めて行きましょう 💪

**Comment by yushi32** [comment]
ふぁらお講師、レビューありがとうございます！
本リリースに向けて引き続き頑張ります！
